package com.yls.bus.sys.dao.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ScheduleJobLogExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table schedule_job_log
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table schedule_job_log
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table schedule_job_log
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule_job_log
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public ScheduleJobLogExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule_job_log
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule_job_log
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule_job_log
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule_job_log
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule_job_log
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule_job_log
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule_job_log
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule_job_log
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule_job_log
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule_job_log
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table schedule_job_log
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andLogIdIsNull() {
			addCriterion("log_id is null");
			return (Criteria) this;
		}

		public Criteria andLogIdIsNotNull() {
			addCriterion("log_id is not null");
			return (Criteria) this;
		}

		public Criteria andLogIdEqualTo(String value) {
			addCriterion("log_id =", value, "logId");
			return (Criteria) this;
		}

		public Criteria andLogIdNotEqualTo(String value) {
			addCriterion("log_id <>", value, "logId");
			return (Criteria) this;
		}

		public Criteria andLogIdGreaterThan(String value) {
			addCriterion("log_id >", value, "logId");
			return (Criteria) this;
		}

		public Criteria andLogIdGreaterThanOrEqualTo(String value) {
			addCriterion("log_id >=", value, "logId");
			return (Criteria) this;
		}

		public Criteria andLogIdLessThan(String value) {
			addCriterion("log_id <", value, "logId");
			return (Criteria) this;
		}

		public Criteria andLogIdLessThanOrEqualTo(String value) {
			addCriterion("log_id <=", value, "logId");
			return (Criteria) this;
		}

		public Criteria andLogIdLike(String value) {
			addCriterion("log_id like", value, "logId");
			return (Criteria) this;
		}

		public Criteria andLogIdNotLike(String value) {
			addCriterion("log_id not like", value, "logId");
			return (Criteria) this;
		}

		public Criteria andLogIdIn(List<String> values) {
			addCriterion("log_id in", values, "logId");
			return (Criteria) this;
		}

		public Criteria andLogIdNotIn(List<String> values) {
			addCriterion("log_id not in", values, "logId");
			return (Criteria) this;
		}

		public Criteria andLogIdBetween(String value1, String value2) {
			addCriterion("log_id between", value1, value2, "logId");
			return (Criteria) this;
		}

		public Criteria andLogIdNotBetween(String value1, String value2) {
			addCriterion("log_id not between", value1, value2, "logId");
			return (Criteria) this;
		}

		public Criteria andJobIdIsNull() {
			addCriterion("job_id is null");
			return (Criteria) this;
		}

		public Criteria andJobIdIsNotNull() {
			addCriterion("job_id is not null");
			return (Criteria) this;
		}

		public Criteria andJobIdEqualTo(String value) {
			addCriterion("job_id =", value, "jobId");
			return (Criteria) this;
		}

		public Criteria andJobIdNotEqualTo(String value) {
			addCriterion("job_id <>", value, "jobId");
			return (Criteria) this;
		}

		public Criteria andJobIdGreaterThan(String value) {
			addCriterion("job_id >", value, "jobId");
			return (Criteria) this;
		}

		public Criteria andJobIdGreaterThanOrEqualTo(String value) {
			addCriterion("job_id >=", value, "jobId");
			return (Criteria) this;
		}

		public Criteria andJobIdLessThan(String value) {
			addCriterion("job_id <", value, "jobId");
			return (Criteria) this;
		}

		public Criteria andJobIdLessThanOrEqualTo(String value) {
			addCriterion("job_id <=", value, "jobId");
			return (Criteria) this;
		}

		public Criteria andJobIdLike(String value) {
			addCriterion("job_id like", value, "jobId");
			return (Criteria) this;
		}

		public Criteria andJobIdNotLike(String value) {
			addCriterion("job_id not like", value, "jobId");
			return (Criteria) this;
		}

		public Criteria andJobIdIn(List<String> values) {
			addCriterion("job_id in", values, "jobId");
			return (Criteria) this;
		}

		public Criteria andJobIdNotIn(List<String> values) {
			addCriterion("job_id not in", values, "jobId");
			return (Criteria) this;
		}

		public Criteria andJobIdBetween(String value1, String value2) {
			addCriterion("job_id between", value1, value2, "jobId");
			return (Criteria) this;
		}

		public Criteria andJobIdNotBetween(String value1, String value2) {
			addCriterion("job_id not between", value1, value2, "jobId");
			return (Criteria) this;
		}

		public Criteria andBeanNameIsNull() {
			addCriterion("bean_name is null");
			return (Criteria) this;
		}

		public Criteria andBeanNameIsNotNull() {
			addCriterion("bean_name is not null");
			return (Criteria) this;
		}

		public Criteria andBeanNameEqualTo(String value) {
			addCriterion("bean_name =", value, "beanName");
			return (Criteria) this;
		}

		public Criteria andBeanNameNotEqualTo(String value) {
			addCriterion("bean_name <>", value, "beanName");
			return (Criteria) this;
		}

		public Criteria andBeanNameGreaterThan(String value) {
			addCriterion("bean_name >", value, "beanName");
			return (Criteria) this;
		}

		public Criteria andBeanNameGreaterThanOrEqualTo(String value) {
			addCriterion("bean_name >=", value, "beanName");
			return (Criteria) this;
		}

		public Criteria andBeanNameLessThan(String value) {
			addCriterion("bean_name <", value, "beanName");
			return (Criteria) this;
		}

		public Criteria andBeanNameLessThanOrEqualTo(String value) {
			addCriterion("bean_name <=", value, "beanName");
			return (Criteria) this;
		}

		public Criteria andBeanNameLike(String value) {
			addCriterion("bean_name like", value, "beanName");
			return (Criteria) this;
		}

		public Criteria andBeanNameNotLike(String value) {
			addCriterion("bean_name not like", value, "beanName");
			return (Criteria) this;
		}

		public Criteria andBeanNameIn(List<String> values) {
			addCriterion("bean_name in", values, "beanName");
			return (Criteria) this;
		}

		public Criteria andBeanNameNotIn(List<String> values) {
			addCriterion("bean_name not in", values, "beanName");
			return (Criteria) this;
		}

		public Criteria andBeanNameBetween(String value1, String value2) {
			addCriterion("bean_name between", value1, value2, "beanName");
			return (Criteria) this;
		}

		public Criteria andBeanNameNotBetween(String value1, String value2) {
			addCriterion("bean_name not between", value1, value2, "beanName");
			return (Criteria) this;
		}

		public Criteria andMethodNameIsNull() {
			addCriterion("method_name is null");
			return (Criteria) this;
		}

		public Criteria andMethodNameIsNotNull() {
			addCriterion("method_name is not null");
			return (Criteria) this;
		}

		public Criteria andMethodNameEqualTo(String value) {
			addCriterion("method_name =", value, "methodName");
			return (Criteria) this;
		}

		public Criteria andMethodNameNotEqualTo(String value) {
			addCriterion("method_name <>", value, "methodName");
			return (Criteria) this;
		}

		public Criteria andMethodNameGreaterThan(String value) {
			addCriterion("method_name >", value, "methodName");
			return (Criteria) this;
		}

		public Criteria andMethodNameGreaterThanOrEqualTo(String value) {
			addCriterion("method_name >=", value, "methodName");
			return (Criteria) this;
		}

		public Criteria andMethodNameLessThan(String value) {
			addCriterion("method_name <", value, "methodName");
			return (Criteria) this;
		}

		public Criteria andMethodNameLessThanOrEqualTo(String value) {
			addCriterion("method_name <=", value, "methodName");
			return (Criteria) this;
		}

		public Criteria andMethodNameLike(String value) {
			addCriterion("method_name like", value, "methodName");
			return (Criteria) this;
		}

		public Criteria andMethodNameNotLike(String value) {
			addCriterion("method_name not like", value, "methodName");
			return (Criteria) this;
		}

		public Criteria andMethodNameIn(List<String> values) {
			addCriterion("method_name in", values, "methodName");
			return (Criteria) this;
		}

		public Criteria andMethodNameNotIn(List<String> values) {
			addCriterion("method_name not in", values, "methodName");
			return (Criteria) this;
		}

		public Criteria andMethodNameBetween(String value1, String value2) {
			addCriterion("method_name between", value1, value2, "methodName");
			return (Criteria) this;
		}

		public Criteria andMethodNameNotBetween(String value1, String value2) {
			addCriterion("method_name not between", value1, value2, "methodName");
			return (Criteria) this;
		}

		public Criteria andParamsIsNull() {
			addCriterion("params is null");
			return (Criteria) this;
		}

		public Criteria andParamsIsNotNull() {
			addCriterion("params is not null");
			return (Criteria) this;
		}

		public Criteria andParamsEqualTo(String value) {
			addCriterion("params =", value, "params");
			return (Criteria) this;
		}

		public Criteria andParamsNotEqualTo(String value) {
			addCriterion("params <>", value, "params");
			return (Criteria) this;
		}

		public Criteria andParamsGreaterThan(String value) {
			addCriterion("params >", value, "params");
			return (Criteria) this;
		}

		public Criteria andParamsGreaterThanOrEqualTo(String value) {
			addCriterion("params >=", value, "params");
			return (Criteria) this;
		}

		public Criteria andParamsLessThan(String value) {
			addCriterion("params <", value, "params");
			return (Criteria) this;
		}

		public Criteria andParamsLessThanOrEqualTo(String value) {
			addCriterion("params <=", value, "params");
			return (Criteria) this;
		}

		public Criteria andParamsLike(String value) {
			addCriterion("params like", value, "params");
			return (Criteria) this;
		}

		public Criteria andParamsNotLike(String value) {
			addCriterion("params not like", value, "params");
			return (Criteria) this;
		}

		public Criteria andParamsIn(List<String> values) {
			addCriterion("params in", values, "params");
			return (Criteria) this;
		}

		public Criteria andParamsNotIn(List<String> values) {
			addCriterion("params not in", values, "params");
			return (Criteria) this;
		}

		public Criteria andParamsBetween(String value1, String value2) {
			addCriterion("params between", value1, value2, "params");
			return (Criteria) this;
		}

		public Criteria andParamsNotBetween(String value1, String value2) {
			addCriterion("params not between", value1, value2, "params");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("status like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("status not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andErrorIsNull() {
			addCriterion("error is null");
			return (Criteria) this;
		}

		public Criteria andErrorIsNotNull() {
			addCriterion("error is not null");
			return (Criteria) this;
		}

		public Criteria andErrorEqualTo(String value) {
			addCriterion("error =", value, "error");
			return (Criteria) this;
		}

		public Criteria andErrorNotEqualTo(String value) {
			addCriterion("error <>", value, "error");
			return (Criteria) this;
		}

		public Criteria andErrorGreaterThan(String value) {
			addCriterion("error >", value, "error");
			return (Criteria) this;
		}

		public Criteria andErrorGreaterThanOrEqualTo(String value) {
			addCriterion("error >=", value, "error");
			return (Criteria) this;
		}

		public Criteria andErrorLessThan(String value) {
			addCriterion("error <", value, "error");
			return (Criteria) this;
		}

		public Criteria andErrorLessThanOrEqualTo(String value) {
			addCriterion("error <=", value, "error");
			return (Criteria) this;
		}

		public Criteria andErrorLike(String value) {
			addCriterion("error like", value, "error");
			return (Criteria) this;
		}

		public Criteria andErrorNotLike(String value) {
			addCriterion("error not like", value, "error");
			return (Criteria) this;
		}

		public Criteria andErrorIn(List<String> values) {
			addCriterion("error in", values, "error");
			return (Criteria) this;
		}

		public Criteria andErrorNotIn(List<String> values) {
			addCriterion("error not in", values, "error");
			return (Criteria) this;
		}

		public Criteria andErrorBetween(String value1, String value2) {
			addCriterion("error between", value1, value2, "error");
			return (Criteria) this;
		}

		public Criteria andErrorNotBetween(String value1, String value2) {
			addCriterion("error not between", value1, value2, "error");
			return (Criteria) this;
		}

		public Criteria andTimesIsNull() {
			addCriterion("times is null");
			return (Criteria) this;
		}

		public Criteria andTimesIsNotNull() {
			addCriterion("times is not null");
			return (Criteria) this;
		}

		public Criteria andTimesEqualTo(String value) {
			addCriterion("times =", value, "times");
			return (Criteria) this;
		}

		public Criteria andTimesNotEqualTo(String value) {
			addCriterion("times <>", value, "times");
			return (Criteria) this;
		}

		public Criteria andTimesGreaterThan(String value) {
			addCriterion("times >", value, "times");
			return (Criteria) this;
		}

		public Criteria andTimesGreaterThanOrEqualTo(String value) {
			addCriterion("times >=", value, "times");
			return (Criteria) this;
		}

		public Criteria andTimesLessThan(String value) {
			addCriterion("times <", value, "times");
			return (Criteria) this;
		}

		public Criteria andTimesLessThanOrEqualTo(String value) {
			addCriterion("times <=", value, "times");
			return (Criteria) this;
		}

		public Criteria andTimesIn(List<String> values) {
			addCriterion("times in", values, "times");
			return (Criteria) this;
		}

		public Criteria andTimesNotIn(List<String> values) {
			addCriterion("times not in", values, "times");
			return (Criteria) this;
		}

		public Criteria andTimesBetween(String value1, String value2) {
			addCriterion("times between", value1, value2, "times");
			return (Criteria) this;
		}

		public Criteria andTimesNotBetween(String value1, String value2) {
			addCriterion("times not between", value1, value2, "times");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table schedule_job_log
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table schedule_job_log
     *
     * @mbggenerated do_not_delete_during_merge Wed Mar 22 14:09:21 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}