package com.yls.bus.sys.dao.entity;

import java.util.Date;

public class ScheduleJobLog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schedule_job_log.log_id
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	private String logId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schedule_job_log.job_id
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	private String jobId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schedule_job_log.bean_name
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	private String beanName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schedule_job_log.method_name
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	private String methodName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schedule_job_log.params
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	private String params;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schedule_job_log.status
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schedule_job_log.error
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	private String error;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schedule_job_log.times
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	private String times;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schedule_job_log.create_time
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schedule_job_log.log_id
	 * @return  the value of schedule_job_log.log_id
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public String getLogId() {
		return logId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schedule_job_log.log_id
	 * @param logId  the value for schedule_job_log.log_id
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public void setLogId(String logId) {
		this.logId = logId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schedule_job_log.job_id
	 * @return  the value of schedule_job_log.job_id
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public String getJobId() {
		return jobId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schedule_job_log.job_id
	 * @param jobId  the value for schedule_job_log.job_id
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public void setJobId(String jobId) {
		this.jobId = jobId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schedule_job_log.bean_name
	 * @return  the value of schedule_job_log.bean_name
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public String getBeanName() {
		return beanName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schedule_job_log.bean_name
	 * @param beanName  the value for schedule_job_log.bean_name
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public void setBeanName(String beanName) {
		this.beanName = beanName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schedule_job_log.method_name
	 * @return  the value of schedule_job_log.method_name
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public String getMethodName() {
		return methodName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schedule_job_log.method_name
	 * @param methodName  the value for schedule_job_log.method_name
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public void setMethodName(String methodName) {
		this.methodName = methodName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schedule_job_log.params
	 * @return  the value of schedule_job_log.params
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public String getParams() {
		return params;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schedule_job_log.params
	 * @param params  the value for schedule_job_log.params
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public void setParams(String params) {
		this.params = params;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schedule_job_log.status
	 * @return  the value of schedule_job_log.status
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schedule_job_log.status
	 * @param status  the value for schedule_job_log.status
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schedule_job_log.error
	 * @return  the value of schedule_job_log.error
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public String getError() {
		return error;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schedule_job_log.error
	 * @param error  the value for schedule_job_log.error
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public void setError(String error) {
		this.error = error;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schedule_job_log.times
	 * @return  the value of schedule_job_log.times
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public String getTimes() {
		return times;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schedule_job_log.times
	 * @param times  the value for schedule_job_log.times
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public void setTimes(String times) {
		this.times = times;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schedule_job_log.create_time
	 * @return  the value of schedule_job_log.create_time
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schedule_job_log.create_time
	 * @param createTime  the value for schedule_job_log.create_time
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}