package com.yls.bus.sys.dao.entity;

import java.util.Date;

public class ScheduleJob {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schedule_job.job_id
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	private String jobId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schedule_job.bean_name
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	private String beanName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schedule_job.method_name
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	private String methodName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schedule_job.params
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	private String params;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schedule_job.cron_expression
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	private String cronExpression;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schedule_job.status
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schedule_job.remark
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schedule_job.create_time
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schedule_job.job_id
	 * @return  the value of schedule_job.job_id
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public String getJobId() {
		return jobId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schedule_job.job_id
	 * @param jobId  the value for schedule_job.job_id
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public void setJobId(String jobId) {
		this.jobId = jobId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schedule_job.bean_name
	 * @return  the value of schedule_job.bean_name
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public String getBeanName() {
		return beanName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schedule_job.bean_name
	 * @param beanName  the value for schedule_job.bean_name
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public void setBeanName(String beanName) {
		this.beanName = beanName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schedule_job.method_name
	 * @return  the value of schedule_job.method_name
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public String getMethodName() {
		return methodName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schedule_job.method_name
	 * @param methodName  the value for schedule_job.method_name
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public void setMethodName(String methodName) {
		this.methodName = methodName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schedule_job.params
	 * @return  the value of schedule_job.params
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public String getParams() {
		return params;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schedule_job.params
	 * @param params  the value for schedule_job.params
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public void setParams(String params) {
		this.params = params;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schedule_job.cron_expression
	 * @return  the value of schedule_job.cron_expression
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public String getCronExpression() {
		return cronExpression;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schedule_job.cron_expression
	 * @param cronExpression  the value for schedule_job.cron_expression
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public void setCronExpression(String cronExpression) {
		this.cronExpression = cronExpression;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schedule_job.status
	 * @return  the value of schedule_job.status
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schedule_job.status
	 * @param status  the value for schedule_job.status
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schedule_job.remark
	 * @return  the value of schedule_job.remark
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schedule_job.remark
	 * @param remark  the value for schedule_job.remark
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schedule_job.create_time
	 * @return  the value of schedule_job.create_time
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schedule_job.create_time
	 * @param createTime  the value for schedule_job.create_time
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public static final String JOB_PARAM_KEY = "JOB_PARAM_KEY";
}