package com.yls.bus.sys.dao.entity;

public class SysConfig {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_config.id
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_config.key
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	private String key;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_config.value
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	private String value;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_config.status
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_config.remark
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_config.id
	 * @return  the value of sys_config.id
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_config.id
	 * @param id  the value for sys_config.id
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_config.key
	 * @return  the value of sys_config.key
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	public String getKey() {
		return key;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_config.key
	 * @param key  the value for sys_config.key
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	public void setKey(String key) {
		this.key = key;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_config.value
	 * @return  the value of sys_config.value
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	public String getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_config.value
	 * @param value  the value for sys_config.value
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_config.status
	 * @return  the value of sys_config.status
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_config.status
	 * @param status  the value for sys_config.status
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_config.remark
	 * @return  the value of sys_config.remark
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_config.remark
	 * @param remark  the value for sys_config.remark
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}