package com.yls.bus.sys.dao.entity;

public class SysRoleMenu {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role_menu.id
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role_menu.role_id
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	private String roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role_menu.menu_id
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	private String menuId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role_menu.id
	 * @return  the value of sys_role_menu.id
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role_menu.id
	 * @param id  the value for sys_role_menu.id
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role_menu.role_id
	 * @return  the value of sys_role_menu.role_id
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	public String getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role_menu.role_id
	 * @param roleId  the value for sys_role_menu.role_id
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role_menu.menu_id
	 * @return  the value of sys_role_menu.menu_id
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	public String getMenuId() {
		return menuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role_menu.menu_id
	 * @param menuId  the value for sys_role_menu.menu_id
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	public void setMenuId(String menuId) {
		this.menuId = menuId;
	}
}