package com.yls.bus.sys.dao.entity;

public class UserMenuView {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user_menu.user_id
     *
     * @mbg.generated Sat Mar 11 11:36:44 CST 2017
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user_menu.menu_perms
     *
     * @mbg.generated Sat Mar 11 11:36:44 CST 2017
     */
    private String menuPerms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user_menu.menu_id
     *
     * @mbg.generated Sat Mar 11 11:36:44 CST 2017
     */
    private String menuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user_menu.user_id
     *
     * @return the value of v_user_menu.user_id
     *
     * @mbg.generated Sat Mar 11 11:36:44 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user_menu.user_id
     *
     * @param userId the value for v_user_menu.user_id
     *
     * @mbg.generated Sat Mar 11 11:36:44 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user_menu.menu_perms
     *
     * @return the value of v_user_menu.menu_perms
     *
     * @mbg.generated Sat Mar 11 11:36:44 CST 2017
     */
    public String getMenuPerms() {
        return menuPerms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user_menu.menu_perms
     *
     * @param menuPerms the value for v_user_menu.menu_perms
     *
     * @mbg.generated Sat Mar 11 11:36:44 CST 2017
     */
    public void setMenuPerms(String menuPerms) {
        this.menuPerms = menuPerms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user_menu.menu_id
     *
     * @return the value of v_user_menu.menu_id
     *
     * @mbg.generated Sat Mar 11 11:36:44 CST 2017
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user_menu.menu_id
     *
     * @param menuId the value for v_user_menu.menu_id
     *
     * @mbg.generated Sat Mar 11 11:36:44 CST 2017
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }
}