package com.yls.bus.sys.dao.mapper;

import com.yls.bus.sys.dao.entity.ScheduleJobLog;
import com.yls.bus.sys.dao.entity.ScheduleJobLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScheduleJobLogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule_job_log
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	int countByExample(ScheduleJobLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule_job_log
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	int deleteByExample(ScheduleJobLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule_job_log
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	int deleteByPrimaryKey(String logId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule_job_log
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	int insert(ScheduleJobLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule_job_log
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	int insertSelective(ScheduleJobLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule_job_log
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	List<ScheduleJobLog> selectByExample(ScheduleJobLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule_job_log
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	ScheduleJobLog selectByPrimaryKey(String logId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule_job_log
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	int updateByExampleSelective(@Param("record") ScheduleJobLog record,
			@Param("example") ScheduleJobLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule_job_log
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	int updateByExample(@Param("record") ScheduleJobLog record, @Param("example") ScheduleJobLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule_job_log
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	int updateByPrimaryKeySelective(ScheduleJobLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule_job_log
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	int updateByPrimaryKey(ScheduleJobLog record);
}