package com.yls.bus.sys.dao.mapper;

import com.yls.bus.sys.dao.entity.ScheduleJob;
import com.yls.bus.sys.dao.entity.ScheduleJobExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScheduleJobMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule_job
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	int countByExample(ScheduleJobExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule_job
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	int deleteByExample(ScheduleJobExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule_job
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	int deleteByPrimaryKey(String jobId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule_job
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	int insert(ScheduleJob record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule_job
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	int insertSelective(ScheduleJob record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule_job
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	List<ScheduleJob> selectByExample(ScheduleJobExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule_job
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	ScheduleJob selectByPrimaryKey(String jobId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule_job
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	int updateByExampleSelective(@Param("record") ScheduleJob record, @Param("example") ScheduleJobExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule_job
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	int updateByExample(@Param("record") ScheduleJob record, @Param("example") ScheduleJobExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule_job
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	int updateByPrimaryKeySelective(ScheduleJob record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule_job
	 * @mbggenerated  Thu Mar 23 13:48:59 CST 2017
	 */
	int updateByPrimaryKey(ScheduleJob record);
}