package com.yls.bus.sys.dao.mapper;

import com.yls.bus.sys.dao.entity.SysConfig;
import com.yls.bus.sys.dao.entity.SysConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysConfigMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_config
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	long countByExample(SysConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_config
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	int deleteByExample(SysConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_config
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_config
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	int insert(SysConfig record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_config
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	int insertSelective(SysConfig record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_config
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	List<SysConfig> selectByExample(SysConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_config
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	SysConfig selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_config
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	int updateByExampleSelective(@Param("record") SysConfig record, @Param("example") SysConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_config
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	int updateByExample(@Param("record") SysConfig record, @Param("example") SysConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_config
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	int updateByPrimaryKeySelective(SysConfig record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_config
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	int updateByPrimaryKey(SysConfig record);
}