package com.yls.bus.sys.dao.mapper;

import com.yls.bus.sys.dao.entity.SysMenuViwe;
import com.yls.bus.sys.dao.entity.SysMenuViweExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysMenuViweMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_sys_menu
     *
     * @mbg.generated Sat Mar 18 09:56:07 CST 2017
     */
    long countByExample(SysMenuViweExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_sys_menu
     *
     * @mbg.generated Sat Mar 18 09:56:07 CST 2017
     */
    int deleteByExample(SysMenuViweExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_sys_menu
     *
     * @mbg.generated Sat Mar 18 09:56:07 CST 2017
     */
    int insert(SysMenuViwe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_sys_menu
     *
     * @mbg.generated Sat Mar 18 09:56:07 CST 2017
     */
    int insertSelective(SysMenuViwe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_sys_menu
     *
     * @mbg.generated Sat Mar 18 09:56:07 CST 2017
     */
    List<SysMenuViwe> selectByExample(SysMenuViweExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_sys_menu
     *
     * @mbg.generated Sat Mar 18 09:56:07 CST 2017
     */
    int updateByExampleSelective(@Param("record") SysMenuViwe record, @Param("example") SysMenuViweExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_sys_menu
     *
     * @mbg.generated Sat Mar 18 09:56:07 CST 2017
     */
    int updateByExample(@Param("record") SysMenuViwe record, @Param("example") SysMenuViweExample example);
}