package com.yls.bus.sys.dao.mapper;

import com.yls.bus.sys.dao.entity.SysMenu;
import com.yls.bus.sys.dao.entity.SysMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysMenuMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	long countByExample(SysMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	int deleteByExample(SysMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	int deleteByPrimaryKey(String menuId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	int insert(SysMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	int insertSelective(SysMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	List<SysMenu> selectByExample(SysMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	SysMenu selectByPrimaryKey(String menuId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	int updateByExampleSelective(@Param("record") SysMenu record, @Param("example") SysMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	int updateByExample(@Param("record") SysMenu record, @Param("example") SysMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	int updateByPrimaryKeySelective(SysMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	int updateByPrimaryKey(SysMenu record);
}