package com.yls.bus.sys.dao.mapper;

import com.yls.bus.sys.dao.entity.SysRoleMenu;
import com.yls.bus.sys.dao.entity.SysRoleMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysRoleMenuMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_menu
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	long countByExample(SysRoleMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_menu
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	int deleteByExample(SysRoleMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_menu
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_menu
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	int insert(SysRoleMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_menu
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	int insertSelective(SysRoleMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_menu
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	List<SysRoleMenu> selectByExample(SysRoleMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_menu
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	SysRoleMenu selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_menu
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	int updateByExampleSelective(@Param("record") SysRoleMenu record, @Param("example") SysRoleMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_menu
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	int updateByExample(@Param("record") SysRoleMenu record, @Param("example") SysRoleMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_menu
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	int updateByPrimaryKeySelective(SysRoleMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_menu
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	int updateByPrimaryKey(SysRoleMenu record);
}