package com.yls.bus.sys.dao.mapper;

import com.yls.bus.sys.dao.entity.SysUser;
import com.yls.bus.sys.dao.entity.SysUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	long countByExample(SysUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	int deleteByExample(SysUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	int deleteByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	int insert(SysUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	int insertSelective(SysUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	List<SysUser> selectByExample(SysUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	SysUser selectByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	int updateByExampleSelective(@Param("record") SysUser record, @Param("example") SysUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	int updateByExample(@Param("record") SysUser record, @Param("example") SysUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	int updateByPrimaryKeySelective(SysUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbg.generated  Thu Mar 09 22:12:03 CST 2017
	 */
	int updateByPrimaryKey(SysUser record);
}