package com.yls.bus.sys.dao.mapper;

import com.yls.bus.sys.dao.entity.UserMenuView;
import com.yls.bus.sys.dao.entity.UserMenuViewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMenuViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_menu
     *
     * @mbg.generated Sat Mar 11 11:36:44 CST 2017
     */
    long countByExample(UserMenuViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_menu
     *
     * @mbg.generated Sat Mar 11 11:36:44 CST 2017
     */
    int deleteByExample(UserMenuViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_menu
     *
     * @mbg.generated Sat Mar 11 11:36:44 CST 2017
     */
    int insert(UserMenuView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_menu
     *
     * @mbg.generated Sat Mar 11 11:36:44 CST 2017
     */
    int insertSelective(UserMenuView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_menu
     *
     * @mbg.generated Sat Mar 11 11:36:44 CST 2017
     */
    List<UserMenuView> selectByExample(UserMenuViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_menu
     *
     * @mbg.generated Sat Mar 11 11:36:44 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserMenuView record, @Param("example") UserMenuViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_menu
     *
     * @mbg.generated Sat Mar 11 11:36:44 CST 2017
     */
    int updateByExample(@Param("record") UserMenuView record, @Param("example") UserMenuViewExample example);
}